version: "3.9" # Specify the Docker Compose version.

services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000 # Map host port 8000 to container port 8000.
    volumes:
      - ./:/usr/src/app:ro # ./: point to current directory, /path: going to sync for this folder if any changes, ro: read only mode for security
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # env:
    #   - ./.env
    environment:
      DATABASE_HOSTNAME: postgres
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: e031031e
      DATABASE_NAME: fastAPI
      DATABASE_USERNAME: postgres
      SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRES_MINUTES: 30

  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: e031031e
      POSTGRES_DB: fastAPI
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
